on:
  push:
    paths:
      - ".github/workflows/test-template.yml"
      - "src/**"
      - "tools/replace-variables.sh"
      - "@RepositoryName.sln"
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: 1

jobs:
  test-commit:
    name: Test Commit ${{ github.sha }}
    runs-on: ubuntu-latest
    if: "!contains(format('{0} {1}', github.event.head_commit.message, github.event.pull_request.title), '[ci-skip]') && github.event.repository.name == 'DSharpPlus.Template'"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Replace Variables
        run: tools/replace-variables.sh "${{ github.repository }}" "${{ github.event.repository.description }}"
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}-${{ github.sha }}.zip
          path: ${{ github.workspace }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
      - name: Build Project
        run: dotnet build
      - name: Build Dockerfile
        run: docker build -t dsharpplus-template:latest .